---
#
# source: https://share.google/aimode/Cw7AZp9TBtTrQPzfd
#
#


name: Sync fork with upstream (github.com/yuriongit/forex-trading-bot.git)

on:
  schedule:
    # Runs everyday at 12:00 am EST
    - cron: '0 5 * * *' # set using UTC time
  workflow_dispatch: # Allows one to manuall trigger the sync anytime via the github actions tab


jobs:
  sync:
    runs-on: ubuntu-latest # github actions uses ubuntu
    permissions:
      contents: write # Grants permission to write to repo

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4 # similar to a ansible module

      - name: Sync upstream changes
        uses: aormsby/Fork-Sync-With-Upstream-action@3.4.1 # similar to a ansible module
        with:
          target_sync_branch: main
          upstream_repository: https://github.com/yuriongit/forex-trading-bot.git # use target repository here
          upstream_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }} # automatically generated by github

          test_mode: true # will stop the action and alert user if failed


      # Error handling
      - name: Handle Sync Failure
        if: failure() && steps.sync_step.outcome == 'failure'
        run: |
          echo "::error::Sync failed! This is likely due to a merge conflict."
          echo "Please manually resolve the conflict by checking out your main branch and pulling upstream/main."
...
